import os

folder = r'c:\Users\gamin\Downloads\KMRPbyJiff'

lines = [
r'#NoEnv',
r'#SingleInstance, Force',
r'SetWorkingDir, %A_ScriptDir%',
r'FileEncoding, UTF-8',
r'',
r'; --- HWID + АКТИВАЦИЯ ---',
r'DriveGet, Serial, Serial, C:\\',
r'Global HWID := Abs(Serial)',
r'Global ExpectedKey := "KEM-" . ((HWID * 3) + 777) . "-" . ((HWID * 7) + 1337)',
r'Global PROMO_SECRET := 7331',
r'Global AppVersion := "1.5"',
r'',
r'; --- ПРОВЕРКА ОБНОВЛЕНИЙ ---',
r'try {',
r'    HttpU := ComObjCreate("WinHttp.WinHttpRequest.5.1")',
r'    HttpU.Open("GET", "https://kemerevopda-default-rtdb.asia-southeast1.firebasedatabase.app/updater.json?t=" . A_TickCount, false)',
r'    HttpU.Send()',
r'    RespU := HttpU.ResponseText',
r'    if (RespU != "null" && RespU != "") {',
r'        RegExMatch(RespU, """version"":\s*""([^""]+)""", MatchVer)',
r'        RegExMatch(RespU, """url"":\s*""([^""]+)""", MatchUrl)',
r'        RegExMatch(RespU, """laws_version"":\s*(\d+)", MatchLawsVer)',
r'        NewVer := MatchVer1',
r'        UpdateUrl := MatchUrl1',
r'        LawsCloudVer := MatchLawsVer1',
r'        if (LawsCloudVer != "") {',
r'            LocalLawsVer := 0',
r'            IniRead, LocalLawsVer, settings.ini, Auth, LawsVer, 0',
r'            if (!FileExist("laws_cache.json") || LocalLawsVer != LawsCloudVer) {',
r'                UrlDownloadToFile, https://kemerevopda-default-rtdb.asia-southeast1.firebasedatabase.app/laws.json, laws_cache.json',
r'                if (!ErrorLevel)',
r'                    IniWrite, %LawsCloudVer%, settings.ini, Auth, LawsVer',
r'            }',
r'        }',
r'        if (NewVer != "" && NewVer != AppVersion) {',
r'            MsgBox, 68, Доступно обновление!, Вышла версия v%NewVer%.`nОбновить?',
r'            IfMsgBox Yes',
r'            {',
r'                UrlDownloadToFile, %UpdateUrl%, KemerovoPDA_new.exe',
r'                if !ErrorLevel {',
r'                    BatContent =',
r'                    (LTrim',
r'                    @echo off',
r'                    timeout /t 2 /nobreak >nul',
r'                    move /y "%A_WorkingDir%\KemerovoPDA_new.exe" "%A_ScriptFullPath%"',
r'                    start "" "%A_ScriptFullPath%"',
r'                    del "`%~f0"',
r'                    )',
r'                    FileDelete, update_pda.bat',
r'                    FileAppend, %BatContent%, update_pda.bat',
r'                    Run, update_pda.bat,, Hide',
r'                    ExitApp',
r'                }',
r'            }',
r'        }',
r'    }',
r'} catch e {',
r'    ; Нет сети — ок',
r'}',
r'',
r'; --- ПРОВЕРКА АКТИВАЦИИ ---',
r'IniRead, SavedKey, settings.ini, Auth, Key, None',
r'Global Activated := false',
r'if (SavedKey = ExpectedKey) {',
r'    Activated := true',
r'} else if (InStr(SavedKey, "|")) {',
r'    Parts := StrSplit(SavedKey, "|")',
r'    if (Parts.MaxIndex() == 3) {',
r'        EKey := Parts[1]',
r'        PExpiry := Parts[2]',
r'        PHash := Parts[3]',
r'        if (EKey = ExpectedKey) {',
r'            CH := 0',
r'            Combined := EKey . PExpiry',
r'            Loop, % StrLen(Combined)',
r'                CH += Asc(SubStr(Combined, A_Index, 1))',
r'            CH := CH * PROMO_SECRET',
r'            if (PHash = CH) {',
r'                if (PExpiry = "NONE") {',
r'                    Activated := true',
r'                } else {',
r'                    NowStr := SubStr(A_Now, 1, 12)',
r'                    if (NowStr <= PExpiry)',
r'                        Activated := true',
r'                    else',
r'                        IniDelete, settings.ini, Auth, Key',
r'                }',
r'            }',
r'        }',
r'    }',
r'}',
r'',
r'if (!Activated) {',
r'    Gui, Auth:+AlwaysOnTop',
r'    Gui, Auth:Font, s10, Segoe UI',
r'    Gui, Auth:Add, Text, x10 y10, Программа заблокирована. Ваш HWID:',
r'    Gui, Auth:Add, Edit, x10 y30 w280 ReadOnly, %HWID%',
r'    Gui, Auth:Add, Text, x10 y65, Ключ активации или промокод (PRO-...):',
r'    Gui, Auth:Add, Edit, x10 y85 w280 vInputKey',
r'    Gui, Auth:Add, Button, x10 y120 w280 h30 gCheckAuth, Разблокировать',
r'    Gui, Auth:Show, w300 h165, Активация Kemerovo PDA',
r'    return',
r'',
r'    CheckAuth:',
r'        Gui, Auth:Submit, NoHide',
r'        Global HWID, ExpectedKey, PROMO_SECRET',
r'        if (InputKey = ExpectedKey) {',
r'            IniWrite, %InputKey%, settings.ini, Auth, Key',
r'            MsgBox, 64, Успех, Ключ успешно активирован!`nПриятной игры.',
r'            ExitApp',
r'        } else if (InputKey != "") {',
r'            try {',
r'                Http := ComObjCreate("WinHttp.WinHttpRequest.5.1")',
r'                Url := "https://kemerevopda-default-rtdb.asia-southeast1.firebasedatabase.app/promos/" . InputKey . ".json"',
r'                Http.Open("GET", Url, false)',
r'                Http.Send()',
r'                Response := Http.ResponseText',
r'                if (Response = "null") {',
r'                    MsgBox, 16, Ошибка, Ключ не найден!',
r'                    return',
r'                }',
r'                RegExMatch(Response, """uses"":\s*(-?\d+)", MatchUses)',
r'                Uses := MatchUses1',
r'                RegExMatch(Response, """expiry"":\s*""([^""]+)""", MatchExpiry)',
r'                Expiry := MatchExpiry1',
r'                if (Uses = "" || Uses == 0) {',
r'                    MsgBox, 16, Ошибка, Промокод недействителен или исчерпан!',
r'                    return',
r'                }',
r'                if (Expiry != "NONE") {',
r'                    NowStr2 := SubStr(A_Now, 1, 12)',
r'                    if (NowStr2 > Expiry) {',
r'                        MsgBox, 16, Ошибка, Срок действия промокода истек!',
r'                        return',
r'                    }',
r'                }',
r'                if (Uses > 0) {',
r'                    NewUses := Uses - 1',
r'                    Http2 := ComObjCreate("WinHttp.WinHttpRequest.5.1")',
r'                    Http2.Open("PATCH", Url, false)',
r'                    Http2.SetRequestHeader("Content-Type", "application/json")',
r'                    Http2.Send("{""uses"":" . NewUses . "}")',
r'                }',
r'                CH := 0',
r'                Combined := ExpectedKey . Expiry',
r'                Loop, % StrLen(Combined)',
r'                    CH += Asc(SubStr(Combined, A_Index, 1))',
r'                CH := CH * PROMO_SECRET',
r'                FinalKey := ExpectedKey . "|" . Expiry . "|" . CH',
r'                IniWrite, %FinalKey%, settings.ini, Auth, Key',
r'                if (Expiry = "NONE")',
r'                    MsgBox, 64, Активация!, Ключ активирован!`nПриятной игры.',
r'                else {',
r'                    FormatTime, PD, %Expiry%00, dd.MM.yyyy в HH:mm',
r'                    MsgBox, 64, Активация!, Активирован до %PD%!`nПриятной игры.',
r'                }',
r'                ExitApp',
r'            } catch e {',
r'                MsgBox, 16, Ошибка, Нет подключения к серверу!',
r'            }',
r'        } else {',
r'            MsgBox, 16, Ошибка, Введите ключ!',
r'        }',
r'    return',
r'',
r'    AuthGuiClose:',
r'        ExitApp',
r'}',
r'',
r'; --- ЗАГРУЖАЕМ БАЗУ ЗАКОНОВ (в auto-execute, до return!) ---',
r'Global LawsDB := []',
r'Global IsLawsOpen := false',
r'if (FileExist("laws_cache.json")) {',
r'    FileRead, LawsFileText, *P65001 laws_cache.json',
r'    try {',
r'        html := ComObjCreate("HTMLFile")',
r'        html.write("<meta http-equiv=''X-UA-Compatible'' content=''IE=edge''>")',
r'        JS := html.parentWindow',
r'        JSON := JS.JSON',
r'        parsed := JSON.parse(LawsFileText)',
r'        Loop % parsed.length {',
r'            item := parsed[A_Index - 1]',
r'            LawsDB.Push({"Category": item.category, "Article": item.article, "Title": item.title, "Text": item.text})',
r'        }',
r'    } catch e {',
r'        ; Ошибка парсинга JSON',
r'    }',
r'}',
r'',
r'; --- ГЛАВНОЕ МЕНЮ (GUI) ---',
r'Global BindCommands := {}',
r'Global IsMenuOpen := false',
r'Global CurrentEditFile := ""',
r'Global CapturedKey := ""',
r'',
r'FileList := ""',
r'Loop, *.txt',
r'{',
r'    FileList .= A_LoopFileName . "|"',
r'}',
r'if (FileList = "") {',
r'    FileAppend,, Биндер.txt',
r'    FileList := "Биндер.txt|"',
r'}',
r'',
r'Gui, +AlwaysOnTop',
r'Gui, Font, s10, Segoe UI',
r'Gui, Add, Text, x10 y10, Выбери профессию:',
r'; НЕ используем gProfChanged при создании DDL — вызовем LoadBinds вручную ниже',
r'Gui, Add, DropDownList, x10 y30 w310 vSelectedProf, %FileList%',
r'Gui, Add, Button, x325 y29 w75 h24 gCreateProfBtn, + Новый',
r'Gui, Add, Text, x10 y65, Список активных биндов:',
r'Gui, Add, ListView, x10 y85 w490 h270 vBindList, Кнопка|Команда (чат)',
r'Gui, Add, Button, x10 y360 w490 h35 gEditBindsBtn, Редактировать бинды в выбранном профиле',
r'',
r'; Загружаем бинды первого профиля',
r'Gui, Submit, NoHide',
r'if (SelectedProf != "")',
r'    LoadBinds(SelectedProf)',
r'',
r'; Теперь включаем обработчик смены профиля',
r'GuiControl, +gProfChanged, SelectedProf',
r'return',
r'',
r'; --- ГОРЯЧАЯ КЛАВИША F2 ---',
r'F2::',
r'    if (!Activated)',
r'        return',
r'    if (IsMenuOpen) {',
r'        Gui, Hide',
r'        IsMenuOpen := false',
r'    } else {',
r'        Gui, Show, w510 h410, Kemerovo PDA - Настройки',
r'        WinSet, AlwaysOnTop, On, Kemerovo PDA - Настройки',
r'        IsMenuOpen := true',
r'    }',
r'return',
r'',
r'; --- СОЗДАНИЕ ПРОФИЛЯ ---',
r'CreateProfBtn:',
r'    InputBox, NewProfName, Новый профиль, Введите название профессии:, , 250, 130',
r'    if (ErrorLevel || NewProfName = "")',
r'        return',
r'    if (!InStr(NewProfName, ".txt"))',
r'        NewProfName .= ".txt"',
r'    if (FileExist(NewProfName)) {',
r'        MsgBox, 16, Ошибка, Такой профиль уже существует!',
r'        return',
r'    }',
r'    FileAppend,, %NewProfName%',
r'    NewFileList := ""',
r'    Loop, *.txt',
r'        NewFileList .= A_LoopFileName . "|"',
r'    GuiControl,, SelectedProf, |%NewFileList%',
r'    GuiControl,, SelectedProf, %NewProfName%',
r'return',
r'',
r'; --- РЕДАКТИРОВАНИЕ БИНДОВ ---',
r'EditBindsBtn:',
r'    Gui, Submit, NoHide',
r'    if (SelectedProf = "") {',
r'        MsgBox, 16, Ошибка, Профиль не выбран!',
r'        return',
r'    }',
r'    Global CurrentEditFile := SelectedProf',
r'    Global CapturedKey := ""',
r'    Gui, Ed:Destroy',
r'    Gui, Ed:+AlwaysOnTop',
r'    Gui, Ed:Font, s10, Segoe UI',
r'    Gui, Ed:Add, Text, x10 y10 w380, Редактирование: %CurrentEditFile%',
r'    Gui, Ed:Add, ListView, x10 y30 w380 h200 vEdBindList gEdListClick, Кнопка|Команда',
r'    Gui, Ed:Add, Button, x310 y235 w80 h25 gEdDeleteBind, Удалить',
r'    Gui, Ed:Add, Text, x10 y270, Текст для отправки:',
r'    Gui, Ed:Add, Edit, x110 y267 w280 vEdCmd',
r'    Gui, Ed:Add, Text, x10 y300, Клавиша:',
r'    Gui, Ed:Add, Hotkey, x110 y297 w280 vCapturedKey',

r'    Gui, Ed:Add, Button, x10 y335 w185 h30 gEdAddBind, + Добавить бинд',
r'    Gui, Ed:Add, Button, x205 y335 w185 h30 gEdSaveBtn, Сохранить и закрыть',
r'    ; Грузим существующие бинды из файла',
r'    Gui, Ed:Default',
r'    Loop, Read, %CurrentEditFile%',
r'    {',
r'        if (A_LoopReadLine = "" || SubStr(Trim(A_LoopReadLine), 1, 1) = ";")',
r'            continue',
r'        parts := StrSplit(A_LoopReadLine, "::")',
r'        if (parts.MaxIndex() >= 2) {',
r'            eKey := Trim(parts[1])',
r'            cmd_raw := parts[2]',
r'            Loop, % parts.MaxIndex() - 2',
r'                cmd_raw .= "::" . parts[A_Index + 2]',
r'            cmd_raw := Trim(cmd_raw)',
r'            ; Убираем обёртку SendChat("...") — фикс: без лишней точки',
r'            cmd := RegExReplace(cmd_raw, "i)SendChat\(""(.*)""\)", "$1")',
r'            LV_Add("", eKey, cmd)',
r'        }',
r'    }',
r'    LV_ModifyCol(1, 80)',
r'    LV_ModifyCol(2, 280)',
r'    Gui, Ed:Show, w400 h375, Редактор биндов',
r'return',
r'',
r'',
r'EdListClick:',
r'    if (A_GuiEvent != "Normal" && A_GuiEvent != "DoubleClick")',
r'        return',
r'    Gui, Ed:Default',
r'    EditingRow := LV_GetNext(0)',
r'    if (EditingRow = 0)',
r'        return',
r'    LV_GetText(selKey, EditingRow, 1)',
r'    LV_GetText(selCmd, EditingRow, 2)',
r'    CapturedKey := selKey',
r'    GuiControl, Ed:, CapturedKey, %CapturedKey%',
r'    GuiControl, Ed:, EdCmd, %selCmd%',
r'return',
r'',
r'EdAddBind:',
r'    Gui, Ed:Submit, NoHide',
r'    if (CapturedKey = "" || EdCmd = "") {',
r'        MsgBox, 16, Ошибка, Захватите кнопку и введите команду!',
r'        return',
r'    }',
r'    Gui, Ed:Default',
r'    if (EditingRow > 0) {',
r'        LV_Modify(EditingRow, "", CapturedKey, EdCmd)',
r'        EditingRow := 0',
r'    } else {',
r'        LV_Add("", CapturedKey, EdCmd)',
r'    }',
r'    GuiControl, Ed:, EdCmd, %A_Space%',
r'    GuiControl, Ed:, CapturedKey,',
r'    CapturedKey := ""',
r'return',
r'',
r'EdDeleteBind:',
r'    Gui, Ed:Default',
r'    RowNumber := LV_GetNext(0)',
r'    if (RowNumber)',
r'        LV_Delete(RowNumber)',
r'return',
r'',
r'EdSaveBtn:',
r'    Gui, Ed:Submit, NoHide',
r'    if (CapturedKey != "" && EdCmd != "") {',
r'        Gosub, EdAddBind',
r'    }',
r'    Gui, Ed:Default',
r'    RowCount := LV_GetCount()',
r'    FileDelete, %CurrentEditFile%',
r'    FileAppend, `; Бинды профиля`n, %CurrentEditFile%',
r'    Loop %RowCount%',
r'    {',
r'        LV_GetText(eKey, A_Index, 1)',
r'        LV_GetText(eCmd, A_Index, 2)',
r'        FileAppend, %eKey%::SendChat("%eCmd%")`n, %CurrentEditFile%',
r'    }',
r'    Gui, Ed:Destroy',
r'    MsgBox, 64, Успех, Бинды сохранены!',
r'    Gosub, ProfChanged',
r'return',
r'',
r'EdGuiClose:',
r'    Gui, Ed:Destroy',
r'return',
r'',
r'; --- СМЕНА ПРОФИЛЯ ---',
r'ProfChanged:',
r'    Gui, Submit, NoHide',
r'    LoadBinds(SelectedProf)',
r'return',
r'',
r'; --- ЗАГРУЗКА БИНДОВ ИЗ ФАЙЛА ---',
r'LoadBinds(FileName) {',
r'    Global BindCommands',
r'    ; Отключаем старые хоткеи',
r'    for key, cmd in BindCommands',
r'        Hotkey, %key%, Off, UseErrorLevel',
r'    BindCommands := {}',
r'    ; Очищаем ListView главного GUI',
r'    Gui, 1:Default',
r'    LV_Delete()',
r'    if (FileName = "")',
r'        return',
r'    Loop, Read, %FileName%',
r'    {',
r'        if (A_LoopReadLine = "" || SubStr(Trim(A_LoopReadLine), 1, 1) = ";")',
r'            continue',
r'        parts := StrSplit(A_LoopReadLine, "::")',
r'        if (parts.MaxIndex() >= 2) {',
r'            key := Trim(parts[1])',
r'            cmd_raw := parts[2]',
r'            Loop, % parts.MaxIndex() - 2',
r'                cmd_raw .= "::" . parts[A_Index + 2]',
r'            cmd_raw := Trim(cmd_raw)',
r'            ; Фикс regex: убрали лишнюю точку перед \)',
r'            cmd := RegExReplace(cmd_raw, "i)SendChat\(""(.*)""\)", "$1")',
r'            LV_Add("", key, cmd)',
r'            BindCommands[key] := cmd',
r'            Hotkey, IfWinActive, ahk_exe RobloxPlayerBeta.exe',
r'            Hotkey, %key%, ActionHandler, On UseErrorLevel',
r'        }',
r'    }',
r'    LV_ModifyCol(1, "AutoHdr")',
r'    LV_ModifyCol(2, "AutoHdr")',
r'}',
r'',
r'; --- ВЫПОЛНЕНИЕ БИНДА ---',
r'ActionHandler:',
r'    targetKey := A_ThisHotkey',
r'    Global BindCommands',
r'    cmd := BindCommands[targetKey]',
r'    if (cmd != "") {',
r'        KeyWait, Alt',
r'        KeyWait, Ctrl',
r'        KeyWait, Shift',
r'        ClipSaved := ClipboardAll',
r'        Clipboard := ""',
r'        Clipboard := cmd',
r'        ClipWait, 1',
r'        SendEvent, {/}',
r'        Sleep, 500',
r'        SendEvent, {Backspace}',
r'        Sleep, 50',
r'        SendEvent, ^v',
r'        Sleep, 150',
r'        SendEvent, {Enter}',
r'        Sleep, 150',
r'        Clipboard := ClipSaved',
r'    }',
r'return',
r'',
r'GuiClose:',
r'    Gui, Hide',
r'    IsMenuOpen := false',
r'return',
r'',
r'; --- СПРАВОЧНИК ЗАКОНОВ (Win+End) ---',
r'#End::',
r'    if (!Activated)',
r'        return',
r'    if (IsLawsOpen) {',
r'        Gui, Laws:Hide',
r'        IsLawsOpen := false',
r'        return',
r'    }',
r'    Gui, Laws:Destroy',
r'    Gui, Laws:+AlwaysOnTop',
r'    Gui, Laws:Font, s10, Segoe UI',
r'    Gui, Laws:Add, Text, x10 y10 w480, Справочник статей (Поиск):',
r'    Gui, Laws:Add, Edit, x10 y30 w290 vSearchBox gSearchLaws',
r'    Gui, Laws:Add, DropDownList, x310 y30 w180 vLawCategory gSearchLaws, Все||УК РФ|КоАП РФ|ГК РФ|ТК РФ|ФЗ О полиции|ФЗ О прокуратуре|УИК РФ|КАС РФ|УПК РФ|Другие ФЗ',
r'    Gui, Laws:Add, ListView, x10 y60 w480 h220 vLawList gLawSelected, Категория|Статья|Название',
r'    Gui, Laws:Add, Text, x10 y290, Текст статьи:',
r'    Gui, Laws:Add, Edit, x10 y310 w480 h150 vLawText ReadOnly Multi',
r'    Gui, Laws:Add, Button, x10 y470 w480 h35 gCopyLaw, Скопировать текст в буфер обмена',
r'    LV_ModifyCol(1, 100)',
r'    LV_ModifyCol(2, 60)',
r'    LV_ModifyCol(3, 300)',
r'    Gosub, SearchLaws',
r'    Gui, Laws:Show, w500 h515, Справочник (Kemerovo PDA)',
r'    IsLawsOpen := true',
r'return',
r'',
r'LawsGuiClose:',
r'    Gui, Laws:Hide',
r'    IsLawsOpen := false',
r'return',
r'',
r'SearchLaws:',
r'    Gui, Laws:Default',
r'    GuiControlGet, sText,, SearchBox',
r'    GuiControlGet, sCat,, LawCategory',
r'    LV_Delete()',
r'    StringLower, sText, sText',
r'    textMatches := []',
r'    for i, law in LawsDB {',
r'        if (sCat != "Все" && law.Category != sCat)',
r'            continue',
r'        lArt := law.Article',
r'        lTitle := law.Title',
r'        lText := law.Text',
r'        StringLower, lArt, lArt',
r'        StringLower, lTitle, lTitle',
r'        StringLower, lText, lText',
r'        if (sText = "") {',
r'            LV_Add("", law.Category, law.Article, law.Title)',
r'        } else if (InStr(lArt, sText) || InStr(lTitle, sText)) {',
r'            LV_Add("", law.Category, law.Article, law.Title)',
r'        } else if (InStr(lText, sText)) {',
r'            textMatches.Push(law)',
r'        }',
r'    }',
r'    if (sText != "" && textMatches.Length() > 0) {',
r'        LV_Add("", "--- В тексте ---", "", "")',
r'        for i, law in textMatches',
r'            LV_Add("", law.Category, law.Article, law.Title)',
r'    }',
r'return',
r'',
r'LawSelected:',
r'    if (A_GuiEvent != "Normal" && A_GuiEvent != "DoubleClick")',
r'        return',
r'    Gui, Laws:Default',
r'    SelRow := LV_GetNext(0)',
r'    if (SelRow = 0)',
r'        return',
r'    LV_GetText(selCat, SelRow, 1)',
r'    if (selCat = "--- В тексте ---")',
r'        return',
r'    LV_GetText(selArt, SelRow, 2)',
r'    for i, law in LawsDB {',
r'        if (law.Category = selCat && law.Article = selArt) {',
r'            GuiControl, Laws:, LawText, % law.Text',
r'            break',
r'        }',
r'    }',
r'return',
r'',
r'CopyLaw:',
r'    Gui, Laws:Default',
r'    GuiControlGet, lTxt,, LawText',
r'    if (lTxt = "")',
r'        return',
r'    Clipboard := lTxt',
r'    ToolTip, Текст скопирован!',
r'    SetTimer, RemoveTip, 2000',
r'return',
r'',
r'RemoveTip:',
r'    ToolTip',
r'    SetTimer, RemoveTip, Off',
r'return',
]

content = '\r\n'.join(lines) + '\r\n'

with open(os.path.join(folder, 'KemerovoPDA.ahk'), 'w', encoding='utf-8-sig', newline='') as f:
    f.write(content)

with open(os.path.join(folder, 'KemerovoPDA.ahk'), 'rb') as f:
    data = f.read()

print('BOM:', data[:3].hex().upper())
print('Has backslash-quote:', b'\\"' in data)
print('Has LawsDB:', b'LawsDB' in data)
print('Has LoadBinds:', b'LoadBinds' in data)
print('Has laws_cache.json:', b'laws_cache.json' in data)
print('Lines:', data.count(b'\r\n'))
print('Done!')
